### PR TITLE
QOL feature, auto pull latest git release version.

### PR DESCRIPTION
**Pull request by worships**
Automatically pulls latest versions, and supports for mirrors. Also modified the file names in the GameConfig example.
Very simple QOL feature, can be modified to move the function in const.py somewhere else if needed.

### CODE REVIEW

**Comment by Windows81** [comment]
Not bad for a first commit!

I see that the example paths are still absolute.  I set my username on Windows as `USERNAME`, so the paths still wouldn't work on other systems.

Have you had the chance to test RFD yet?

**Comment by worships** [comment]
Yes! I have, also not my first commit, cause this is a new account, old one got banned, no reason why and github wont respond. 

Anyways, thank you and yeah, I could just change it to be a more simple path and I get what you were going for, honestly you could just outright remove the file paths and put a comment.

**Comment by Windows81** [comment]
I'll take that in.

**Comment by Windows81** [comment]
I apologise for the reversal.  I had to revert changes.

`consts.py` should *only* contains constants.  I also doubt that RFD.exe can be updated in-place.

**Comment by worships** [comment]
Ah, its okay I totally understand, and yeah.

**Comment by Windows81** [comment]
No problem.  I just edited the comment above.

**Pull request merged**
